version: '3'
services:
  core_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "corecpicontainer"
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
    env_file:
      - .env