version: '3'
services:
  core_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "coreapicontainer"
    ports:
      - "8000:15400"
    volumes:
      - ./app/:/app
    env_file:
      - .env